name: machine-learning-env

channels: 
  - defaults

dependencies:
  - ipython == 8.15.0
  - matplotlib == 3.8.0
  - pandas == 2.1.1
  - pip == 23.3
  - python == 3.9.18
  - scipy == 1.11.3
  - notebook < 7.0.0
  - nb_conda
  - numpy == 1.26.0
  - seaborn == 0.12.2
  - joblib == 1.2.0
  - geopandas == 0.12.2
  - plotly == 5.9.0
  - GitPython == 3.1.37
  - pip:
    - ephem == 4.1.5
    - shapely == 2.0.2
    - pycmap == 0.2.19
    - contextily == 1.4.0
    - scikit-learn == 1.3.0 
    - forestci == 0.4