name: machine-learning-env

dependencies:
  - ipython
  - matplotlib
  - pandas
  - pip
  - python
  - scikit-learn
  - matplotlib
 
  - numpy

  - seaborn
  - joblib
  
  - geopandas

 
  - plotly
  - GitPython
  - pip:
    - pycmap
    - contextily
    - sklearn.ensemble
    - os
    - sklearn.metrics
    - sklearn.model_selection
    - shapely.geometryf